language: c
compiler:
  - gcc
  - clang

install: 
    - git clone https://github.com/cvra/lwip_ucos2.git ../lwip_ucos2
    
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make; cd ..; ./run_tests.sh
